version: '3'
services:
  wrs_simulator:
    image: wrs_simulator_docker:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
      ROS_MASTER_URI: http://172.16.200.72:11311
      ROS_IP: 172.16.200.72
    working_dir: /catkin_ws
    network_mode: "host"
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: roslaunch hsrb_wrs_gazebo_launch rcj24_final_gpsr.launch
